# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor
x_1 = torch.rand(7,7)
x_1

tensor([[0.9239, 0.7868, 0.8894, 0.0139, 0.4445, 0.6605, 0.2713],
        [0.8818, 0.4822, 0.0809, 0.1605, 0.4990, 0.6915, 0.3039],
        [0.9738, 0.7368, 0.1859, 0.3204, 0.5657, 0.3559, 0.5525],
        [0.1497, 0.5742, 0.5873, 0.2369, 0.7803, 0.7362, 0.7339],
        [0.6776, 0.7154, 0.0183, 0.1597, 0.7846, 0.2789, 0.0328],
        [0.7383, 0.9647, 0.7910, 0.8003, 0.6973, 0.2800, 0.5149],
        [0.3749, 0.9014, 0.2329, 0.6220, 0.5287, 0.4979, 0.8489]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
x_2 = torch.rand(1,7)
x_2

# Perform matrix multiplication
x_result = torch.matmul(x_1, x_2.T)
x_result

tensor([[2.7747],
        [1.2309],
        [1.9414],
        [2.4421],
        [2.3308],
        [1.8755],
        [1.5360]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
x_1_seed = torch.rand(7,7)
x_2_seed = torch.rand(1,7)

# Matrix multiply tensors
x_result_seed = torch.matmul(x_1_seed, x_2_seed.T)
x_result_seed

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
# Create two random tensors on GPU
if torch.cuda.is_available():
    tensor_1 = torch.rand(2,3)
    tensor_1 = tensor_1.to('cuda')
    tensor_2 = torch.rand(2,3)
    tensor_2 = tensor_2.to('cuda')
    print("GPU is available")
else:
    print("GPU is not available")

GPU is available



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor_result = torch.matmul(tensor_1, tensor_2.T)
tensor_result

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
tensor_max = torch.max(tensor_result)
tensor_max

tensor(0.5617, device='cuda:0')

In [ ]:
# Find min
tensor_min = torch.min(tensor_result)
tensor_min

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
tensor_argmax = torch.argmax(tensor_result)
tensor_argmax

tensor(3, device='cuda:0')

In [ ]:
# Find arg min
tensor_argmin = torch.argmin(tensor_result)
tensor_argmin

tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(0)

# Create random tensor
tensor_multidim = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_monodim = torch.rand(10)

# Print out tensors and their shapes
tensor_multidim, tensor_monodim

(tensor([[[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964,
            0.4556, 0.6323]]]]),
 tensor([0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000, 0.1610,
         0.2823]))

In [ ]:
tensor_multidim.shape, tensor_monodim.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))